version: "3"

services:

  eclipse:
    container_name: eclipse-clp
    tty: true
    build:
      context: ./eclipse
      args:
        eclipse_version: ${ECLIPSE_VERSION}
    env_file:
      - .env
    volumes:
      - ../src:/root/eclipseclp
